### ISSUE TITLE
meld won't load for terminal only based systems alternative?

### ISSUE THREAD

**Issue by NonaSuomy** [Ashark/archlinux-amdgpu-pro#64]
./extract_transaction_scripts_and_triggers.sh
Opening meld for comparison...
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
2020-11-26 14:47:48,772 CRITICAL Gtk: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/bin/meld", line 384, in <module>
    setup_resources()
  File "/usr/bin/meld", line 236, in setup_resources
    Gtk.IconTheme.get_default().append_search_path(icon_dir)
AttributeError: 'NoneType' object has no attribute 'append_search_path'

**Comment by chaw0023** [comment]
I am getting exact same error with Meld v3.20.1. Is someone working on this issue?

`~/$ meld
2022-02-16 00:51:57,586 CRITICAL Gtk: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "Meldbin/meld", line 364, in <module>
    setup_resources()
  File "Meld/bin/meld", line 236, in setup_resources
    Gtk.IconTheme.get_default().append_search_path(icon_dir)
AttributeError: 'NoneType' object has no attribute 'append_search_path'
`

**Comment by Ashark** [comment]
Thanks for the report. I decided to just skip this step starting from 22.10.3 update.
